spring:
  application:
    name: spring-cloud-consul-producer-2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: service-producer
# \u6CE8\u518C\u5230 consul \u7684\u670D\u52A1\u540D\u79F0
server:
  port: 8502
